package Kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import Kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.20 16:00:07 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi41 */
  @Test
  public void testRekisteroi41() {    // Kirja: 41
    Kirja k1 = new Kirja(); 
    assertEquals("From: Kirja line: 43", 0, k1.getId()); 
    k1.rekisteroi(); 
    Kirja k2 = new Kirja(); 
    k2.rekisteroi(); 
    int n1 = k1.getId(); 
    int n2 = k2.getId(); 
    assertEquals("From: Kirja line: 49", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi70 */
  @Test
  public void testGetNimi70() {    // Kirja: 70
    Kirja metro = new Kirja(); 
    metro.tayta_metro(); 
    { String _l_=metro.getNimi(),_r_="Metro .*"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 73" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END
}