package kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.28 14:07:21 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** testGetNimi32 */
  @Test
  public void testGetNimi32() {    // Kirja: 32
    Kirja metro = new Kirja(); 
    metro.tayta(); 
    { String _l_=metro.getNimi(),_r_="Metro .*"; if ( !_l_.matches(_r_) ) fail("From: Kirja line: 35" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi91 */
  @Test
  public void testRekisteroi91() {    // Kirja: 91
    Kirja k1 = new Kirja(); 
    assertEquals("From: Kirja line: 93", 0, k1.getId()); 
    k1.rekisteroi(); 
    Kirja k2 = new Kirja(); 
    k2.rekisteroi(); 
    int n1 = k1.getId(); 
    int n2 = k2.getId(); 
    assertEquals("From: Kirja line: 99", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString133 */
  @Test
  public void testToString133() {    // Kirja: 133
    Kirja k = new Kirja(); 
    k.parse("2  |Metro 2033      |2         |2         |2005 |Artjom seikkailee metrossa"); 
    assertEquals("From: Kirja line: 136", true, k.toString().startsWith("2|Metro 2033|2|2|2005|Artjom seikkailee metrossa")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse153 */
  @Test
  public void testParse153() {    // Kirja: 153
    Kirja k = new Kirja(); 
    k.parse("3  |What if?        |3         |3         |2014 |Absurdeja hypoteettisiä kysymyksiä"); 
    assertEquals("From: Kirja line: 156", 3, k.getId()); 
    assertEquals("From: Kirja line: 157", true, k.toString().startsWith("3|What if?|3|3|2014|Absurdeja hypoteettisiä kysymyksiä")); 
    k.rekisteroi(); 
    int n = k.getId(); 
    k.parse(""+(n+20)); 
    k.rekisteroi(); 
    assertEquals("From: Kirja line: 165", n+20+1, k.getId()); 
  } // Generated by ComTest END
}