package kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.11 18:19:57 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjailijaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi82 */
  @Test
  public void testRekisteroi82() {    // Kirjailija: 82
    Kirjailija kir1 = new Kirjailija(); 
    assertEquals("From: Kirjailija line: 84", 0, kir1.getId()); 
    kir1.rekisteroi(); 
    Kirjailija kir2 = new Kirjailija(); 
    kir2.rekisteroi(); 
    int n1 = kir1.getId(); 
    int n2 = kir2.getId(); 
    assertEquals("From: Kirjailija line: 90", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString133 */
  @Test
  public void testToString133() {    // Kirjailija: 133
    Kirjailija kir = new Kirjailija(); 
    kir.parse("2  |Dmitri Gluhovski"); 
    assertEquals("From: Kirjailija line: 136", "2|Dmitri Gluhovski", kir.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse150 */
  @Test
  public void testParse150() {    // Kirjailija: 150
    Kirjailija kir = new Kirjailija(); 
    kir.parse("3  |Randall Munroe"); 
    assertEquals("From: Kirjailija line: 153", 3, kir.getId()); 
    assertEquals("From: Kirjailija line: 154", "3|Randall Munroe", kir.toString()); 
    kir.rekisteroi(); 
    int n = kir.getId(); 
    kir.parse("" + (n+20)); 
    kir.rekisteroi(); 
    assertEquals("From: Kirjailija line: 159", n+20+1, kir.getId()); 
    assertEquals("From: Kirjailija line: 160", "" + (n+20+1) + "|Randall Munroe", kir.toString()); 
  } // Generated by ComTest END
}