package kirjahylly.test;

// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import java.util.Collection;
import java.util.Iterator;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.28 14:16:16 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjahyllyTest {

    // Generated by ComTest BEGIN
    /** testLisaa33 */
    @Test
    public void testLisaa33() { // Kirjahylly: 33
        Kirjahylly hylly = new Kirjahylly();
        Kirja k1 = new Kirja(), k2 = new Kirja();
        try {
            hylly.lisaa(k1);
            hylly.lisaa(k2);
            hylly.lisaa(k1);
            Collection<Kirja> loytyneet = hylly.etsi("", 0, -1);
            Iterator<Kirja> it = loytyneet.iterator();
            assertEquals("From: Kirjahylly line: 45", k1, it.next());
            assertEquals("From: Kirjahylly line: 46", k2, it.next());
            assertEquals("From: Kirjahylly line: 47", k1, it.next());
        } catch (SailoException e) {
            k1.toString(); // pelkkä // ei riitä koska comTest ei vie sitä
                           // mukanaan
        }
    } // Generated by ComTest END
}