package kirjahylly.test;
// Generated by ComTest BEGIN
import kirjahylly.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.28 15:48:31 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa43 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa43() throws SailoException {    // Kirjat: 43
    Kirjat kirjat = new Kirjat(); 
    Kirja k1 = new Kirja(), k2 = new Kirja(); 
    assertEquals("From: Kirjat line: 47", 0, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 48", 1, kirjat.getLkm()); 
    kirjat.lisaa(k2); assertEquals("From: Kirjat line: 49", 2, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 50", 3, kirjat.getLkm()); 
    assertEquals("From: Kirjat line: 51", k1, kirjat.anna(0)); 
    assertEquals("From: Kirjat line: 52", k2, kirjat.anna(1)); 
    assertEquals("From: Kirjat line: 53", k1, kirjat.anna(2)); 
    assertEquals("From: Kirjat line: 54", false, kirjat.anna(1) == k1); 
    assertEquals("From: Kirjat line: 55", true, kirjat.anna(1) == k2); 
    try {
    assertEquals("From: Kirjat line: 56", k1, kirjat.anna(3)); 
    fail("Kirjat: 56 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 57", 4, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 58", 5, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 59", 6, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 60", 7, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 61", 8, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 62", 9, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 63", 10, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 64", 11, kirjat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testKirjatIterator239 
   * @throws SailoException when error
   */
  @Test
  public void testKirjatIterator239() throws SailoException {    // Kirjat: 239
    Kirjat kirjat = new Kirjat(); 
    Kirja k1 = new Kirja(), k2 = new Kirja(); 
    k1.rekisteroi(); k2.rekisteroi(); 
    kirjat.lisaa(k1); 
    kirjat.lisaa(k2); 
    kirjat.lisaa(k1); 
    StringBuffer ids = new StringBuffer(30); 
    for (Kirja k:kirjat) // Kokeillaan for-silmukan toimintaa
    ids.append(" " + k.getId()); 
    String tulos = " " + k1.getId() + " " + k2.getId() + " " + k1.getId(); 
    assertEquals("From: Kirjat line: 258", tulos, ids.toString()); 
    ids = new StringBuffer(30); 
    for (Iterator<Kirja>  i=kirjat.iterator(); i.hasNext(); ) { // ja iteraattorin toimintaa
    Kirja k = i.next(); 
    ids.append(" " + k.getId()); 
    }
    assertEquals("From: Kirjat line: 266", tulos, ids.toString()); 
    Iterator<Kirja>  i=kirjat.iterator(); 
    assertEquals("From: Kirjat line: 269", true, i.next() == k1); 
    assertEquals("From: Kirjat line: 270", true, i.next() == k2); 
    assertEquals("From: Kirjat line: 271", true, i.next() == k1); 
    try {
    i.next(); 
    fail("Kirjat: 273 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testEtsi332 
   * @throws SailoException when error
   */
  @Test
  public void testEtsi332() throws SailoException {    // Kirjat: 332
    Kirjat kirjat = new Kirjat(); 
    Kirja k1 = new Kirja(); k1.parse("1|Ready Player One|1|1|"); 
    Kirja k2 = new Kirja(); k2.parse("2|Metro 2033|2|2|"); 
    Kirja k3 = new Kirja(); k3.parse("3|What if?|3|3|"); 
    Kirja k4 = new Kirja(); k4.parse("4|Metro 2035|2|4|"); 
    Kirja k5 = new Kirja(); k5.parse("5|Diaspora|4|5|"); 
    kirjat.lisaa(k1); kirjat.lisaa(k2); kirjat.lisaa(k3); kirjat.lisaa(k4); kirjat.lisaa(k5); 
  } // Generated by ComTest END
}