package kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.25 21:00:17 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjahyllyTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa36 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa36() throws SailoException {    // Kirjahylly: 36
    Kirjahylly hylly = new Kirjahylly(); 
    Kirja m1 = new Kirja(), m2 = new Kirja(); 
    m1.rekisteroi(); 
    m2.rekisteroi(); 
    assertEquals("From: Kirjahylly line: 42", 0, hylly.getKirjat()); 
    hylly.lisaa(m1); assertEquals("From: Kirjahylly line: 43", 1, hylly.getKirjat()); 
    hylly.lisaa(m2); assertEquals("From: Kirjahylly line: 44", 2, hylly.getKirjat()); 
    hylly.lisaa(m1); assertEquals("From: Kirjahylly line: 45", 3, hylly.getKirjat()); 
    assertEquals("From: Kirjahylly line: 46", 3, hylly.getKirjat()); 
    assertEquals("From: Kirjahylly line: 47", m1, hylly.annaKirja(0)); 
    assertEquals("From: Kirjahylly line: 48", m2, hylly.annaKirja(1)); 
    assertEquals("From: Kirjahylly line: 49", m1, hylly.annaKirja(2)); 
    try {
    assertEquals("From: Kirjahylly line: 50", m1, hylly.annaKirja(3)); 
    fail("Kirjahylly: 50 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    hylly.lisaa(m1); assertEquals("From: Kirjahylly line: 51", 4, hylly.getKirjat()); 
    hylly.lisaa(m1); assertEquals("From: Kirjahylly line: 52", 5, hylly.getKirjat()); 
    hylly.lisaa(m1); assertEquals("From: Kirjahylly line: 53", 6, hylly.getKirjat()); 
    hylly.lisaa(m1); assertEquals("From: Kirjahylly line: 54", 7, hylly.getKirjat()); 
    hylly.lisaa(m1); assertEquals("From: Kirjahylly line: 55", 8, hylly.getKirjat()); 
    hylly.lisaa(m1); assertEquals("From: Kirjahylly line: 56", 9, hylly.getKirjat()); 
    hylly.lisaa(m1); assertEquals("From: Kirjahylly line: 57", 10, hylly.getKirjat()); 
    try {
    hylly.lisaa(m1); 
    fail("Kirjahylly: 58 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}