package kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.02.25 20:32:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa28 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa28() throws SailoException {    // Kirjat: 28
    Kirjat kirjat = new Kirjat(); 
    Kirja k1 = new Kirja(), k2 = new Kirja(); 
    assertEquals("From: Kirjat line: 32", 0, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 33", 1, kirjat.getLkm()); 
    kirjat.lisaa(k2); assertEquals("From: Kirjat line: 34", 2, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 35", 3, kirjat.getLkm()); 
    assertEquals("From: Kirjat line: 36", k1, kirjat.anna(0)); 
    assertEquals("From: Kirjat line: 37", k2, kirjat.anna(1)); 
    assertEquals("From: Kirjat line: 38", k1, kirjat.anna(2)); 
    assertEquals("From: Kirjat line: 39", false, kirjat.anna(1) == k1); 
    assertEquals("From: Kirjat line: 40", true, kirjat.anna(1) == k2); 
    try {
    assertEquals("From: Kirjat line: 41", k1, kirjat.anna(3)); 
    fail("Kirjat: 41 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 42", 4, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 43", 5, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 44", 6, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 45", 7, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 46", 8, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 47", 9, kirjat.getLkm()); 
    kirjat.lisaa(k1); assertEquals("From: Kirjat line: 48", 10, kirjat.getLkm()); 
    try {
    kirjat.lisaa(k1); 
    fail("Kirjat: 49 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}