package kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.11 21:15:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KirjaTest {



  // Generated by ComTest BEGIN
  /** 
   * testClone33 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone33() throws CloneNotSupportedException {    // Kirja: 33
    Kirja kirja = new Kirja(); 
    kirja.parse("1|Maailman ympäri|40"); 
    Kirja kopio = kirja.clone(); 
    Object olio = kirja.clone(); 
    assertEquals("From: Kirja line: 39", kirja.toString(), kopio.toString()); 
    kirja.parse("2|Maailman ympäri|40"); 
    assertEquals("From: Kirja line: 41", false, kopio.toString().equals(kirja.toString())); 
    assertEquals("From: Kirja line: 42", true, olio instanceof Kirja); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi64 */
  @Test
  public void testGetNimi64() {    // Kirja: 64
    Kirja metro = new Kirja(); 
    metro.tayta(); 
    assertEquals("From: Kirja line: 67", "", metro.getNimi()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi169 */
  @Test
  public void testRekisteroi169() {    // Kirja: 169
    Kirja k1 = new Kirja(); 
    assertEquals("From: Kirja line: 171", 0, k1.getId()); 
    k1.rekisteroi(); 
    Kirja k2 = new Kirja(); 
    k2.rekisteroi(); 
    int n1 = k1.getId(); 
    int n2 = k2.getId(); 
    assertEquals("From: Kirja line: 177", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString211 */
  @Test
  public void testToString211() {    // Kirja: 211
    Kirja k = new Kirja(); 
    k.parse("2  |Metro 2033      |2         |2         |2005 |Artjom seikkailee metrossa"); 
    assertEquals("From: Kirja line: 214", true, k.toString().startsWith("2|Metro 2033|2|2|2005|Artjom seikkailee metrossa")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse231 */
  @Test
  public void testParse231() {    // Kirja: 231
    Kirja k = new Kirja(); 
    k.parse("3  |What if?        |3         |3         |2014 |Absurdeja hypoteettisiä kysymyksiä"); 
    assertEquals("From: Kirja line: 234", 3, k.getId()); 
    assertEquals("From: Kirja line: 235", true, k.toString().startsWith("3|What if?|3|3|2014|Absurdeja hypoteettisiä kysymyksiä")); 
    k.rekisteroi(); 
    int n = k.getId(); 
    k.parse(""+(n+20)); 
    k.rekisteroi(); 
    assertEquals("From: Kirja line: 243", n+20+1, k.getId()); 
  } // Generated by ComTest END
}