package kirjahylly.test;
// Generated by ComTest BEGIN
import java.io.File;
import kirjahylly.*;
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END

import kanta.SailoException;

/**
 * Test class made by ComTest
 * @version 2020.04.11 21:26:38 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KustantajatTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa63 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa63() throws SailoException {    // Kustantajat: 63
    Kustantajat kustantajat = new Kustantajat(); 
    Kustantaja kus1 = new Kustantaja(), kus2 = new Kustantaja(); 
    assertEquals("From: Kustantajat line: 67", 0, kustantajat.getLkm()); 
    kustantajat.lisaa(kus1); assertEquals("From: Kustantajat line: 68", 1, kustantajat.getLkm()); 
    kustantajat.lisaa(kus2); assertEquals("From: Kustantajat line: 69", 2, kustantajat.getLkm()); 
    kustantajat.lisaa(kus1); assertEquals("From: Kustantajat line: 70", 3, kustantajat.getLkm()); 
    Iterator<Kustantaja> it = kustantajat.iterator(); 
    assertEquals("From: Kustantajat line: 72", kus1, it.next()); 
    assertEquals("From: Kustantajat line: 73", kus2, it.next()); 
    assertEquals("From: Kustantajat line: 74", kus1, it.next()); 
    kustantajat.lisaa(kus1); assertEquals("From: Kustantajat line: 75", 4, kustantajat.getLkm()); 
    kustantajat.lisaa(kus1); assertEquals("From: Kustantajat line: 76", 5, kustantajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testPoista100 
   * @throws SailoException when error
   */
  @Test
  public void testPoista100() throws SailoException {    // Kustantajat: 100
    Kustantajat kustantajat = new Kustantajat(); 
    Kustantaja kus1 = new Kustantaja(), kus2 = new Kustantaja(), kus3 = new Kustantaja(); 
    kus1.rekisteroi(); kus2.rekisteroi(); kus3.rekisteroi(); 
    int id1 = kus1.getId(); 
    kustantajat.lisaa(kus1); kustantajat.lisaa(kus2); kustantajat.lisaa(kus3); 
    kustantajat.poista(id1+1); 
    kustantajat.poista(id1); assertEquals("From: Kustantajat line: 108", 1, kustantajat.getLkm()); 
    kustantajat.poista(id1+3); assertEquals("From: Kustantajat line: 109", 1, kustantajat.getLkm()); 
    kustantajat.poista(id1+2); assertEquals("From: Kustantajat line: 110", 0, kustantajat.getLkm()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testLueTiedostosta155 
   * @throws SailoException when error
   */
  @Test
  public void testLueTiedostosta155() throws SailoException {    // Kustantajat: 155
    Kustantajat kustantajat = new Kustantajat(); 
    Kustantaja k21 = new Kustantaja(); k21.tayta(2); 
    Kustantaja k11 = new Kustantaja(); k11.tayta(1); 
    Kustantaja k22 = new Kustantaja(); k22.tayta(2); 
    Kustantaja k12 = new Kustantaja(); k12.tayta(1); 
    Kustantaja k23 = new Kustantaja(); k23.tayta(2); 
    String tiedNimi = "tmp_testihylly_kustantajat"; 
    File ftied = new File(tiedNimi+".dat"); 
    ftied.delete(); 
    try {
    kustantajat.lueTiedostosta(tiedNimi); 
    fail("Kustantajat: 167 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
    kustantajat.lisaa(k21); 
    kustantajat.lisaa(k11); 
    kustantajat.lisaa(k22); 
    kustantajat.lisaa(k12); 
    kustantajat.lisaa(k23); 
    kustantajat.tallenna(); 
    kustantajat = new Kustantajat(); 
    kustantajat.lueTiedostosta(tiedNimi); 
    Iterator<Kustantaja> i = kustantajat.iterator(); 
    assertEquals("From: Kustantajat line: 177", k21.toString(), i.next().toString()); 
    assertEquals("From: Kustantajat line: 178", k11.toString(), i.next().toString()); 
    assertEquals("From: Kustantajat line: 179", k22.toString(), i.next().toString()); 
    assertEquals("From: Kustantajat line: 180", k12.toString(), i.next().toString()); 
    assertEquals("From: Kustantajat line: 181", k23.toString(), i.next().toString()); 
    assertEquals("From: Kustantajat line: 182", false, i.hasNext()); 
    kustantajat.lisaa(k23); 
    kustantajat.tallenna(); 
    assertEquals("From: Kustantajat line: 185", true, ftied.delete()); 
    File fbak = new File(tiedNimi+".backup"); 
    assertEquals("From: Kustantajat line: 187", true, fbak.delete()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testIterator317 */
  @Test
  public void testIterator317() {    // Kustantajat: 317
    Kustantajat kustantajat = new Kustantajat(); 
    Kustantaja p12 = new Kustantaja(2); kustantajat.lisaa(p12); 
    Kustantaja p21 = new Kustantaja(1); kustantajat.lisaa(p21); 
    Kustantaja p32 = new Kustantaja(2); kustantajat.lisaa(p32); 
    Kustantaja p41 = new Kustantaja(1); kustantajat.lisaa(p41); 
    Kustantaja p52 = new Kustantaja(2); kustantajat.lisaa(p52); 
    Iterator<Kustantaja> i2 = kustantajat.iterator(); 
    assertEquals("From: Kustantajat line: 329", p12, i2.next()); 
    assertEquals("From: Kustantajat line: 330", p21, i2.next()); 
    assertEquals("From: Kustantajat line: 331", p32, i2.next()); 
    assertEquals("From: Kustantajat line: 332", p41, i2.next()); 
    assertEquals("From: Kustantajat line: 333", p52, i2.next()); 
    try {
    assertEquals("From: Kustantajat line: 334", p21, i2.next()); 
    fail("Kustantajat: 334 Did not throw NoSuchElementException");
    } catch(NoSuchElementException _e_){ _e_.getMessage(); }
    int n = 0; 
    int jnrot[] = { 2,1,2,1,2} ; 
    for ( Kustantaja kus : kustantajat ) {
    assertEquals("From: Kustantajat line: 340", jnrot[n], kus.getId()); n++; 
    }
    assertEquals("From: Kustantajat line: 343", 5, n); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnnaKustantaja357 */
  @Test
  public void testAnnaKustantaja357() {    // Kustantajat: 357
    Kustantajat kustantajat = new Kustantajat(); 
    Kustantaja pete = new Kustantaja(0); kustantajat.lisaa(pete); 
    Kustantaja vesa = new Kustantaja(1); kustantajat.lisaa(vesa); 
    Kustantaja tupu = new Kustantaja(2); kustantajat.lisaa(tupu); 
    Kustantaja hupu = new Kustantaja(3); kustantajat.lisaa(hupu); 
    Kustantaja lupu = new Kustantaja(4); kustantajat.lisaa(lupu); 
    Kustantaja rupu = new Kustantaja(5); kustantajat.lisaa(rupu); 
    Kustantaja etsitty = new Kustantaja(); 
    etsitty = kustantajat.annaKustantaja(0); 
    assertEquals("From: Kustantajat line: 371", true, etsitty == pete); 
    etsitty = kustantajat.annaKustantaja(1); 
    assertEquals("From: Kustantajat line: 373", true, etsitty == vesa); 
    etsitty = kustantajat.annaKustantaja(2); 
    assertEquals("From: Kustantajat line: 375", true, etsitty == tupu); 
    etsitty = kustantajat.annaKustantaja(3); 
    assertEquals("From: Kustantajat line: 377", true, etsitty == hupu); 
    etsitty = kustantajat.annaKustantaja(4); 
    assertEquals("From: Kustantajat line: 379", true, etsitty == lupu); 
    etsitty = kustantajat.annaKustantaja(5); 
    assertEquals("From: Kustantajat line: 381", true, etsitty == rupu); 
  } // Generated by ComTest END
}