package kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.03.28 14:53:30 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KustantajaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi73 */
  @Test
  public void testRekisteroi73() {    // Kustantaja: 73
    Kustantaja kus1 = new Kustantaja(); 
    assertEquals("From: Kustantaja line: 75", 0, kus1.getId()); 
    kus1.rekisteroi(); 
    Kustantaja kus2 = new Kustantaja(); 
    kus2.rekisteroi(); 
    int n1 = kus1.getId(); 
    int n2 = kus2.getId(); 
    assertEquals("From: Kustantaja line: 81", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString124 */
  @Test
  public void testToString124() {    // Kustantaja: 124
    Kustantaja kus = new Kustantaja(); 
    kus.parse("1  |Random House"); 
    assertEquals("From: Kustantaja line: 127", "1|Random House", kus.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse141 */
  @Test
  public void testParse141() {    // Kustantaja: 141
    Kustantaja kus = new Kustantaja(); 
    kus.parse("5  |Orion Publishing Group"); 
    assertEquals("From: Kustantaja line: 144", 5, kus.getId()); 
    assertEquals("From: Kustantaja line: 145", "5|Orion Publishing Group", kus.toString()); 
    kus.rekisteroi(); 
    int n = kus.getId(); 
    kus.parse("" + (n+20)); 
    kus.rekisteroi(); 
    assertEquals("From: Kustantaja line: 151", n+20+1, kus.getId()); 
    assertEquals("From: Kustantaja line: 152", "" + (n+20+1) + "|Orion Publishing Group", kus.toString()); 
  } // Generated by ComTest END
}