package kirjahylly.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import kirjahylly.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.11 18:20:09 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class KustantajaTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi82 */
  @Test
  public void testRekisteroi82() {    // Kustantaja: 82
    Kustantaja kus1 = new Kustantaja(); 
    assertEquals("From: Kustantaja line: 84", 0, kus1.getId()); 
    kus1.rekisteroi(); 
    Kustantaja kus2 = new Kustantaja(); 
    kus2.rekisteroi(); 
    int n1 = kus1.getId(); 
    int n2 = kus2.getId(); 
    assertEquals("From: Kustantaja line: 90", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString133 */
  @Test
  public void testToString133() {    // Kustantaja: 133
    Kustantaja kus = new Kustantaja(); 
    kus.parse("1  |Random House"); 
    assertEquals("From: Kustantaja line: 136", "1|Random House", kus.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse150 */
  @Test
  public void testParse150() {    // Kustantaja: 150
    Kustantaja kus = new Kustantaja(); 
    kus.parse("5  |Orion Publishing Group"); 
    assertEquals("From: Kustantaja line: 153", 5, kus.getId()); 
    assertEquals("From: Kustantaja line: 154", "5|Orion Publishing Group", kus.toString()); 
    kus.rekisteroi(); 
    int n = kus.getId(); 
    kus.parse("" + (n+20)); 
    kus.rekisteroi(); 
    assertEquals("From: Kustantaja line: 160", n+20+1, kus.getId()); 
    assertEquals("From: Kustantaja line: 161", "" + (n+20+1) + "|Orion Publishing Group", kus.toString()); 
  } // Generated by ComTest END
}