package kanta.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import static kanta.apu.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.10 21:28:39 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class apuTest {



  // Generated by ComTest BEGIN
  /** testTarkistaEtteiTyhja29 */
  @Test
  public void testTarkistaEtteiTyhja29() {    // apu: 29
    assertEquals("From: apu line: 30", false, tarkistaEtteiTyhja("")); 
    assertEquals("From: apu line: 31", true, tarkistaEtteiTyhja(".")); 
    assertEquals("From: apu line: 32", true, tarkistaEtteiTyhja("dsiafaöhioawhpä")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaPvm47 */
  @Test
  public void testTarkistaPvm47() {    // apu: 47
    assertEquals("From: apu line: 48", true, tarkistaPvm("31.12.9999")); 
    assertEquals("From: apu line: 49", false, tarkistaPvm("32.12.9999")); 
    assertEquals("From: apu line: 50", false, tarkistaPvm("31.13.9999")); 
    assertEquals("From: apu line: 51", false, tarkistaPvm("31.12.10000")); 
    assertEquals("From: apu line: 52", true, tarkistaPvm("1.1.0000")); 
    assertEquals("From: apu line: 53", false, tarkistaPvm("0.1.0000")); 
    assertEquals("From: apu line: 54", false, tarkistaPvm("1.0.0000")); 
    assertEquals("From: apu line: 55", false, tarkistaPvm("1.1.000")); 
    assertEquals("From: apu line: 56", true, tarkistaPvm("")); 
    assertEquals("From: apu line: 57", true, tarkistaPvm("2.2.2222")); 
    assertEquals("From: apu line: 58", true, tarkistaPvm("02.02.2222")); 
    assertEquals("From: apu line: 59", false, tarkistaPvm("kissa")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaVuosi74 */
  @Test
  public void testTarkistaVuosi74() {    // apu: 74
    assertEquals("From: apu line: 75", false, tarkistaVuosi("")); 
    assertEquals("From: apu line: 76", true, tarkistaVuosi("6969")); 
    assertEquals("From: apu line: 77", false, tarkistaVuosi("420")); 
    assertEquals("From: apu line: 78", false, tarkistaVuosi("42666")); 
    assertEquals("From: apu line: 79", false, tarkistaVuosi("koira")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testTarkistaNumeerisuus92 */
  @Test
  public void testTarkistaNumeerisuus92() {    // apu: 92
    assertEquals("From: apu line: 93", false, tarkistaNumeerisuus("")); 
    assertEquals("From: apu line: 94", true, tarkistaNumeerisuus("1")); 
    assertEquals("From: apu line: 95", false, tarkistaNumeerisuus("Hyvä")); 
    assertEquals("From: apu line: 96", false, tarkistaNumeerisuus("Huono")); 
    assertEquals("From: apu line: 97", false, tarkistaNumeerisuus("Viisi")); 
    assertEquals("From: apu line: 98", false, tarkistaNumeerisuus("5/5")); 
    assertEquals("From: apu line: 99", true, tarkistaNumeerisuus("12")); 
  } // Generated by ComTest END
}